### ISSUE TITLE
pass custom value in callbacks?

### ISSUE THREAD

**Issue by breakintheweb** [JohMun/vue-tags-input#10]
First of all, great component! 

Is it possible to do a callback on creation/deletion with a custom value? I have a v-for loop that reuses this component multiple times. I'd like to pass the index of the item in my v-for to a custom function on creation/deletion of a tag.

Thank you,

**Comment by breakintheweb** [comment]
I ended up figuring out a solution. 
```
   <vue-tags-input
                    class="tags-input"
                    v-model="row.tag"
                    :tags=row.tags"
                    @tags-changed="updateRowTags(index,...arguments)"        
                  />
```
and then in methods:
```
   updateRowTags (rowindex,tags) {
      
        this.rows[rowindex].tags = tags
// api call to update db here
}
```

**Comment by JohMun** [comment]
@breakintheweb Looks fine to me. That is what a would have recommended. Just change the models data in your component and don't call internal vue-tags-input functions, for example with `ref`, to add/delete tags.
