### ISSUE TITLE
How to change 'add tag' words ?

### ISSUE THREAD

**Issue by fightlikeagirl** [JohMun/vue-tags-input#102]
How to change 'add tag' words ? I looked but didn't find. Thank You

**Comment by gamazu** [comment]
> How to change 'add tag' words ? I looked but didn't find. Thank You

Just use a placeholder prop 

`<vue-tags-input`
`v-model="tag"`
`:tags="tags"`
`@tags-changed="newTags => tags = newTags"`
 ` :validation="validation"`
`placeholder="{Put your text here}"  `
 ` />`

**Comment by fightlikeagirl** [comment]
Thank you so much that was easy @gamazu
