### ISSUE TITLE
Problem with multiple vue-tag-inputs on the same page

### ISSUE THREAD

**Issue by fredzv** [JohMun/vue-tags-input#119]
Hi,

I would like to use vue-tags-input for each row in a table that is constructed by data i get from an API to tag each entry. Issue is that every time I want to add a tag in one of the inputs it starts typing in all of them. This is due to the data property "tag" that I'm passing to the v-model of the input. I'm declaring it just like the example: tag: ''.
Is there any way to circumvent this? If I had a fixed amount of inputs I'd just create another data property like tag1 and tag2 but for my case the number is dynamic.

**Comment by smartnio** [comment]
Hey,

it's rare that i comment a solution, but most of the time others are always faster :D
But i ran into the same issue, so here is my solution.

This behaviour is not vue-tag-inputs fault. If you just straight copy and paste the code from the examples and put a vue-tag-input inside a for loop, you bind multiple inputs to one value.
https://stackoverflow.com/questions/52530434/use-v-model-inside-a-v-for-loop

Create an empty array in your data-return function tag:[ ] (use array insteaed of a string as suggested in the examples) and use v-model="tag[index]" on your vue-tag-inputs. This should work for dynamic use cases. It works for me :+1:

**Comment by fredzv** [comment]
Works perfectly thank you! A very nice clean solution.

**Comment by smartnio** [comment]
Glad to hear! :)

I ended up wrapping each vue-tag-inputs inside a new component and used it without the array/object hack. It's an even easier way. ^^
