### ISSUE TITLE
How to show a disabled tag in autocomplete

### ISSUE THREAD

**Issue by ty7466** [JohMun/vue-tags-input#13]
Is it possible to display a tag that is disabled in the autocomplete?

**Comment by JohMun** [comment]
Something like that is not supported currently:
```
autocompleteItems: [{
  text: 'a Tag is disabled',
  disabled: true,
}, {
  text: 'another tag',
}]
````
I think I will add this functionality in the future.

For now, you can do something else to get the job done. Use the [validation feature](http://www.vue-tags-input.com/#/examples/validation) with the property `disableAdd: true`.

I made an example on [codepen](https://codepen.io/JohMun/pen/NzMmaP).

**Comment by JohMun** [comment]
Another way would be to use the [before-adding-tag hook](http://www.vue-tags-input.com/#/examples/hooks).  Register a callback function like in the example and do a check, if the tag should be added or not.
