### ISSUE TITLE
Library status question :)

### ISSUE THREAD

**Issue by roberto910907** [JohMun/vue-tags-input#134]
@JohMun First of all, thank you for spending the time on building this amazing library.

We've been researching on a good library that can help us to handle tags in our project and we found this project, but we're wondering if some help is needed in order to move forward and work on the open issues and PRs. 

I totally understand the effort behind maintaining an open source library but now that the Hacktoberfest is coming it might be a good opportunity to give back a little bit of what we've received from the community and specially from open source projects like this.

I'm wondering if you have a plan in mind about how to continue to support the library or if it would be better if we fork it and work on a separate repository.

Looking forward to hearing from you! Again, thanks.

**Comment by JohMun** [comment]
Hey there,

in the last months I hadn't the time to care about this project. But in the next weeks, I take a look at the issues, PRs and enhancements. So, the repo is not dead and I increase the support, soon!

Greetings
