### ISSUE TITLE
Idea: Per item option for "allow-edit-tags"

### ISSUE THREAD

**Issue by bally86** [JohMun/vue-tags-input#136]
Hi,

Thanks for the great package! 

I use it to let the user create it's own combined product title.
The user can search for product fields from the autocomplete list combined with it's own input.
For example: [product_id] - [product_title] | customtext

The tags [product_id] and [product_title] are selected from the autocomplete list and the other data is user input.
What I want a achieve now is that the fields added by autocomplete cannot be edited and the own user input can be edited.
Therefore it would be great to have a per tag option for "allow-edit-tags" so that some tags can be edited and some can't.

**Comment by JohMun** [comment]
Therefor you can use the `before-editing-tag` hook. Give the tags from autocomplete some property e.g. `edit: false`. Then in the callback function of `before-editing-tag`, you do somehting like this:
```
beforeEditingTag(handler) {
  if (handler.tag.edit === undefined) handler.editTag();
}
```

**Comment by bally86** [comment]
That is amazing! Thank you for the fast reply!
Another question then; How can I define the default properties for newly added tags? For example classes or this edit property.

**Comment by JohMun** [comment]
You registered a callback function on `@tags-changed`. If you copied the example it looks like this:
```
@tags-changed="newTags => tags = newTags"
```

But you can do whatever you like, to the tags array.
```
@tags-changed="handleChange"
```
```
handleChange(tags) {
  this.tags = tags.map(t => ({ ...t, anotherProp: Math.random() }));
}
```

**Comment by bally86** [comment]
Okay, thanks for all the support!
