### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, got Null

### ISSUE THREAD

**Issue by spazer5** [JohMun/vue-tags-input#17]
Great module!

However there's an issue with it throwing an error:

`[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, got Null`

It works perfectly, but I don't want to keep seeing this error on the console.

the `value` prop doesn't seem to be documented either, and it's set as a  `required` string in the module's codebase. but the docs just suggest using `v-model`

Any ideas?

**Comment by JohMun** [comment]
If you pass a value with `v-model` to vue-tags-input, the component recieves this value via the prop `value`. So I suppose, that your model, which is binded to `v-model`, holds the value `null` sometimes.

**Comment by JohMun** [comment]
@spazer5 did you find a solution? Then I would close this issue.
