### ISSUE TITLE
Comma [44], semicolon [59] not working as "addOnKey" values

### ISSUE THREAD

**Issue by pokluda** [JohMun/vue-tags-input#18]
Hey JohMun,

first of all thanks for a great component! 😃

I was wondering why the comma and/or semicolon wouldn't work as "addOnKey"s.
```
v-bind:addOnKey="[9, 13, 32, 44, 59]"
```
(the enter, space and tab work just fine)

We're using the component for multiple email input and it might be quite natural for some people to separate them by a comma/semicolon.

We do have the separators defined too:
```
v-bind:separators="[',', ';']"
```
so multiple entries get processed just fine eventually but it would be nice if they were validated as-you-go when a comma/semicolon is pressed.

Cheers,
Jacob

**Comment by JohMun** [comment]
Hi pokluda,

I think you are using a wrong keycode. Try it with 188.

```
:addOnKey="[9, 13, 32, 188]"
```

**Comment by pokluda** [comment]
aaah I was looking at the ASCII codes instead of the JS char/key codes.

sorry about that mate, thanks heaps for the hint! 👍
