### ISSUE TITLE
Add option to edit more information about the tag.

### ISSUE THREAD

**Issue by xmnlab** [JohMun/vue-tags-input#20]
Hi everyone!

I need to link the click event on the tag and create/open a div panel that allow user to edit more information related to the tag selected.

how can I do that? 

my best regards.

**Comment by JohMun** [comment]
Hi,

it seems to me, that you need an event like `@tag-clicked="myCallbackFn"` and `myCallbackFn` 
gets the clicked tag as a parameter. Currently vue-tags-input doesn't support this feature in that way 
(I add it in the future).

For now, you can abuse the `@before-editing-tag` event to achieve that. I made a [codepen](https://codepen.io/JohMun/pen/OwMWQB?editors=1111) for you.

**Comment by JohMun** [comment]
@xmnlab Just click on a tag and input fields show up to edit two properties.  When it is in edit mode, you really should disable vue-tags-input, like in the example.

**Comment by xmnlab** [comment]
@JohMun It seems very nice! thank you so much!
