### ISSUE TITLE
Hide placeholder after fill out Max Tags

### ISSUE THREAD

**Issue by Flow999Cloud** [JohMun/vue-tags-input#21]
Thanks for your sharing great work. @JohMun 

I just wanted to know if is there anyway we can hide the placeholder letters after we fill out max tags.
Can you let me know please if this functionality has already been implemented or we need to make a PR for it?

Thanks in advance.

**Comment by JohMun** [comment]
Hi Flow999Cloud,

you can change the placeholer tags in every way you like. For example, set it dynamically based on the tag's arrays length:

```
<template>
  <div>
    <vue-tags-input
      v-model="tag"
      :tags="tags"
      :max-tags="maxTags"
      :placeholder="placeholderText"
      @tags-changed="newTags => tags = newTags"
    />
  </div>
</template>

<script>
import VueTagsInput from '@johmun/vue-tags-input';

export default {
  components: {
    VueTagsInput,
  },
  data() {
    return {
      tag: '',
      tags: [],
      maxTags: 3,
    };
  },
  computed: {
    placeholderText: () => this.tags && this.tags.length >= this.maxTags ? '' : 'Add a tag',
  },
};
</script>
```

**Comment by Flow999Cloud** [comment]
Awesome, thanks. @JohMun 
Really appreciate for your help.
