### ISSUE TITLE
Use autocomplete-items and hooks together

### ISSUE THREAD

**Issue by jic5760** [JohMun/vue-tags-input#22]
If use autocomplete-items and hooks together,
than autocomplete-item click is not working.
just v-model variable have user input text.
Thanks

**Comment by JohMun** [comment]
I am not sure what you mean exactly. Can you please show me an example on codepen, how you use vue-tags-input?

**Comment by JohMun** [comment]
Or paste some code here, if it's easier for you

**Comment by jic5760** [comment]
<vue-tags-input
                                    v-model="temp_tag"
                                    :tags="tags"
                                    :autocomplete-items="tagsFilteredItems"
                                    @tags-changed="newTags => tags = newTags"
                                    @before-adding-tag="obj => taginput_handler = obj.addTag">
                            </vue-tags-input>

data:
tagsFilteredItems: [{text: 'Spain'}, {text: 'USA'}]

methods:
taginput_handler: function() {
                var input = this.temp_tag; ///
            }

If I type 'Spa' then vue-tags-input show me 'Spain'
And If I click, called taginput_handler method.
But var input only have 'Spa' not 'Spain'

**Comment by jic5760** [comment]
https://codepen.io/jic5760/pen/YjpYwG

**Comment by JohMun** [comment]
In your example on codepen, `taginput_handler` is a variable, defined in `data` and a `method` at the same time. That will cause trouble ... 

If you keep `taginput_handler` just as a variable and assign `obj.addTag` in the `@before-adding-tag` hook, like you did. Then you can call `this.taginput_handler()` somewhere in your code and the tag will be added (if someone tries to add one with e.g. via autocomplete). 
Is that what you are trying to achieve?

Maybe a look at the [examples](http://www.vue-tags-input.com/#/examples/hooks) will help you.

**Comment by jic5760** [comment]
Thank you.
I've resolved through the code below.

(vue-tags-input)
@before-adding-tag="beforeAddingTagHandler"

(vue method)
beforeAddingTahHandler: function(e){
  console.log(e.tag.text); // complete tag text!
  e.addTag();
}
