### ISSUE TITLE
Feature request I quess

### ISSUE THREAD

**Issue by picitujeromanov** [JohMun/vue-tags-input#23]
Is it possible to have an option to show dropdown on text input focus? 
So it doesn't always show like 'autocomplete-always-open' option, but shows when user focus on text input but he didn't start typing yet

**Comment by JohMun** [comment]
Hey,

set the prop `autocomplete-min-length` to `0`. I think it's the behaviour you are looking for.

**Comment by picitujeromanov** [comment]
Oh yes, perfect, thank you very much
