### ISSUE TITLE
Invalid prop: custom validator check failed for prop "tags".

### ISSUE THREAD

**Issue by Abdulsametileri** [JohMun/vue-tags-input#24]
First of all, Great compenent. Thank you so much. 

I wondered. Why I get this error? I did not use validator, I wanna send 
[ {text: 'Bla bla' }, {text: 'Bla bla2' }, {text: 'Bla bla3' } ] this array. But I get this error. I did not write any validation on these elements..

**Comment by Abdulsametileri** [comment]
I solved this problem. Some elements has text property empty string "".. How can i disable this custom validator?

**Comment by JohMun** [comment]
The custom validator checks all props received by vue-tags-input. It verifies that the props have the correct type or the expected input format. There is no option to disable the validator, because it is just a helper for the development, which warns, that vue-tags-input will crash if props with an unexpected type or input are in use.

**Comment by Abdulsametileri** [comment]
Thank you for your interest. How can i get return value of before-adding-tag, before-deleting-tag, before-editing-tag. I wanna add AddTag(obj), EditTag(obj) etc... obj means added or edited tag..

**Comment by Abdulsametileri** [comment]
Thank you so much. I have one more question. I used v-for.. I wanna pass index of for and some object parameters too. But ı get error. How can i pass parameters to these functions? 
@before-adding-tag="addingTag"
@before-saving-tag="saveTag"

addingTag(obj: any, index: number, arg: string) {
    console.log(obj.tag)
    obj.addTag();
},

**Comment by JohMun** [comment]
At default, the registered callback function for `@before-adding-tag` or `@before-saving-tag` gets an object as parameter. The object contains a tag and a funtion, depending on the hook, see [events](http://www.vue-tags-input.com/#/api/events).

**Comment by ultrasamad** [comment]
So what proptype does it expects? I'm pushing string items onto the array of tags and I keep getting that error.

**Comment by Abdulsametileri** [comment]
default model is {text: '', tiClasses: ['valid']. If you pass an array of objects, the objects have to be text: string , tiClasses:[] property to avoid validator errors. I solve this problem in this way

**Comment by ultrasamad** [comment]
@Abdulsametileri Yh thanks. I had to also create a model with the text property, not sure however what the `tiClasses:[]` means.

**Comment by JohMun** [comment]
@ultrasamad You must not create tag objects on your on. I think [this](http://www.vue-tags-input.com/#/api/create-tags-helper) will help you.

**Comment by eg0170** [comment]
@JohMun follow up here: I want to pass existing tags through Vue. I am currently trying to do this through a prop but getting the same error. What is the best way to invoke those helpers?

Thanks

**Comment by JohMun** [comment]
@eg0170 Here is an example, how to create tag objects outside of vue-tags-input:

```html
<div>
  <vue-tags-input
    v-model="tag"
    :tags="tags"
    :validation="validation"
    @tags-changed="newTags => tags = newTags"
  />
</div>
```

```javascript
import { VueTagsInput, createTags } from '@johmun/vue-tags-input';

export default {
  components: {
    VueTagsInput,
  },
  data() {
    return {
      tag: '',
      // tags is overwritten in the created hook
      tags: null,
      validation: [{
        // no-number is added as css-class to a tag, if the tag has no numbers in the text
        classes: 'no-number',
        rule: /[0-9]/
      }]
    };
  },
  created() {
    // the first param of createTags() is the tags array, 
    // the second one is the validation array
    this.tags = createTags([{
      text: 'My tag 1'
    }, {
      text: 'Another Tag'
    }], this.validation);
  },
};
```
_______________________
`createTags` returns validated tag objects which will roughly look like the following:
```javascript
{ 
  "text": "Another Tag", 
  "tiClasses": [ "no-number", "ti-invalid" ] 
}
```

**Comment by eg0170** [comment]
@JohMun  thanks! Unfortunately I am hitting the following errors, just by having a created() method:


`    created() {
            console.log('test');          
        },
`

`[Vue warn]: Error in created hook: "TypeError: __WEBPACK_IMPORTED_MODULE_0__johmun_vue_tags_input___default(...) is not a function"

found in

---> <Tags> at resources/assets/js/components/Tags.vue
       <VueJsModal> at src/Modal.vue
         <VideoView> at resources/assets/js/pages/Video.vue
           <Root>
warn @ utils.js:41
logError @ utils.js:41
globalHandleError @ utils.js:41
handleError @ utils.js:41
callHook @ utils.js:41
Vue._init @ utils.js:41
VueComponent @ utils.js:41
createComponentInstanceForVnode @ utils.js:41
init @ utils.js:41
createComponent @ utils.js:41
createElm @ utils.js:41
createChildren @ utils.js:41
createElm @ utils.js:41
createChildren @ utils.js:41
createElm @ utils.js:41
createChildren @ utils.js:41
createElm @ utils.js:41
createChildren @ utils.js:41
createElm @ utils.js:41
patch @ utils.js:41
Vue._update @ utils.js:41
updateComponent @ utils.js:41
get @ utils.js:41
run @ utils.js:41
flushSchedulerQueue @ utils.js:41
(anonymous) @ utils.js:41
flushCallbacks @ utils.js:41
Promise.then (async)
microTimerFunc @ utils.js:41
nextTick @ utils.js:41
queueWatcher @ utils.js:41
update @ utils.js:41
notify @ utils.js:41
reactiveSetter @ utils.js:41
(anonymous) @ utils.js:41
setTimeout (async)
visible @ utils.js:41
run @ utils.js:41
flushSchedulerQueue @ utils.js:41
(anonymous) @ utils.js:41
flushCallbacks @ utils.js:41
utils.js:41 TypeError: __WEBPACK_IMPORTED_MODULE_0__johmun_vue_tags_input___default(...) is not a function
    at VueComponent.created (utils.js:41)
    at callHook (utils.js:41)
    at VueComponent.Vue._init (utils.js:41)
    at new VueComponent (utils.js:41)
    at createComponentInstanceForVnode (utils.js:41)
    at init (utils.js:41)
    at createComponent (utils.js:41)
    at createElm (utils.js:41)
    at createChildren (utils.js:41)
    at createElm (utils.js:41)`

**Comment by eg0170** [comment]
Thank you @JohMun

**Comment by suhailkc** [comment]
I have the same issue. and fixed it by adding `"tiClasses":["ti-valid"]` 

 Example: 
`tags: [ {"text":"London","tiClasses":["ti-valid"]}, {"text":"Cananda","tiClasses":["ti-valid"]}, 
 {"text":"Australia","tiClasses":["ti-valid"]}, {"text":"Mexico","tiClasses":["ti-valid"]}]`
