### ISSUE TITLE
Android - keydown events / addOnKeys

### ISSUE THREAD

**Issue by jsm174** [JohMun/vue-tags-input#31]
In a project I am working on, we are using 

```
:add-on-key="addOnKeys"
``` 

to allow creating tags with enter, comma, and semicolon:

```
computed: {
    	 addOnKeys: function() {
    		var isFirefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
    		 
    		return [13, (!isFirefox) ? 186 : 59, 188];
    	 }, 
```

During testing, we noticed that on Android devices, tags will not be created when a user touches those keys.

After research, event keyCodes have been a long standing issue with Android. When the user touches most keys, the keyCode is 229. (Delete and enter return the correct keyCodes.) 

We came up with a solution, but we are trying to avoid using a custom version of the plugin. 

We changed the keydown event to keyup:

```
            @keyup="performAddTags(
              filteredAutocompleteItems[selectedItem] || newTag, $event
            )"
```

Then we modified `noTriggerKey` to see if the keyCode is 229. If it is, we look at the last character of the input field. If it was a comma or a semicolon, we change the keyCode accordingly:

```
    noTriggerKey: function noTriggerKey(event, category) {
      var keyCode = event.keyCode;
      if (keyCode == 229) {
        var charAt = event.target.value.charAt(event.target.value.length - 1).charAt();
        if (charAt == ',') {
          keyCode = 188;
        } else if (charAt == ';') {
          keyCode = 186;
        }
      }
      var triggerKey = this[category].indexOf(keyCode) !== -1;
      if (triggerKey) event.preventDefault();
      return !triggerKey;
    },
```

Although this works, it is far from an elegant solution.

**Comment by JohMun** [comment]
Hi, it's been a long time :D (sry for that) 

Maybe your issue can be solved with #47. Assign `[';', ',', 13]` to the `addOnKey` prop and hopefully it works.

**Comment by JohMun** [comment]
okay, i close this now

**Comment by fureszk** [comment]
Unfortunately, it still not works well with android keyboards.
The recommended assign did not help either. No reactions for comma and/or enter, only blur adds them, but only if its not triggered by "tab".
