### ISSUE TITLE
How to modify CSS for autocomplete div ? I have more than 500+ items

### ISSUE THREAD

**Issue by maverickpravin** [JohMun/vue-tags-input#33]
I have a list of 500+ items in autocomplete list. I wanted to modify autocomplete div to a smaller size in height..How can i do that?

**Comment by JohMun** [comment]
Hi, I made an [example](https://codepen.io/JohMun/pen/EdVQgR?editors=1111) for you, how to achieve that. I think, I will add this as feature in the next release, that the autocomplete layer can't grow so big.
