### ISSUE TITLE
Fat arrows doesn't seem to work on IE11, is there an alternative for that?

### ISSUE THREAD

**Issue by byronhabana** [JohMun/vue-tags-input#34]

**Comment by JohMun** [comment]
If you like to use fat arrow functions in your project and need IE11 support, you can use [babel](https://babeljs.io/) to convert your code for older browsers. Another solution would be, don't use ES6+ syntax and write code which can be interpreted by IE11. [Here](http://es6-features.org/#Constants) is an explanation, about the differences between ES6 and older syntax.
