### ISSUE TITLE
:avoidAddingDuplicates="false" is still marking tags as duplicates

### ISSUE THREAD

**Issue by hoppities** [JohMun/vue-tags-input#35]
```
                    <vue-tags-input :tags="selectedTags"
                                    v-model="typeaheadSearchTerm"
                                    :add-only-from-autocomplete="true"
                                    :avoidAddingDuplicates="false"
                                    :autocomplete-filter-duplicates="false"
                                    :autocomplete-items="usersList"
                                    placeholder="Search Users"
                                    :separators="[';',',']"
                                    @before-adding-tag="beforeAddingTag"
                                    @before-deleting-tag="beforeDeletingTag" />
```

I've tried using `avoid-adding-duplicates` and `avoidAddingDuplicates`. Both show the property is set to false, but it's still adding the invalid and duplicate classes to the tag.

**Comment by JohMun** [comment]
The prop `avoid-adding-duplicates` just handles, that the user can't create duplicate tags with the input. If the developer creates a tags array like ```[{ text: '1' }, { text: '1' }]```, the component will add the duplicate and invalid classes to the tags. Does this answer your question?

**Comment by hoppities** [comment]
Yeah, I guess that makes sense. It would seem, though, that if I allow adding duplicates, I would not want them marked with that class as a duplicate.

**Comment by JohMun** [comment]
Why not? I don't think it's an issue, because you must not style duplicate tags if you don't want to, but you are able to, if you like. If I remove the class in the described case, some devs wouldn't have the chance to show a hint to the user, that he is adding a duplicate. Because maybe, the scenario is, that duplicates are not desirable, but allowed.
