### ISSUE TITLE
Can you complete a tag with "," instead of enter?

### ISSUE THREAD

**Issue by burlesona** [JohMun/vue-tags-input#37]
I'm looking for a tag component that I can use to enter multiple email addresses similar to the way they work in Apple Mail (and presumably many other email clients).

These act just like tags with autocomplete, except that instead of hitting enter to "confirm" an email address you just type a comma and the email becomes a "tag."

Is that possible via your component? I didn't see any way to configure it but if it would be an easy tweak I thought I'd ask. Thanks for the cool component!

**Comment by JohMun** [comment]
Yes it's possible. You can specify keycodes which defines, if an input becomes a tag or not.  For example like that: ```add-on-key="[13,188]"``` If the user presses enter or comma, a new tag is generated out of the input.
