### ISSUE TITLE
Avoid duplicates in autocomplete, but do not compare by 'text'

### ISSUE THREAD

**Issue by fikkatra** [JohMun/vue-tags-input#38]
I use an autocomplete to show suggestions. Each suggestion (item) has a label (text) and a category. I'd like to prevent duplicates, but the problem is that in my case, the text values of two different tags can be the same, although they really are different tags (different categories). E.g. I have two tags, both have the text 'Beatle', but one has a category 'Animal' and the other has a category 'Car'.

The user should be able to select both tags, but each tag only once. This cannot be done by setting the properties `autocomplete-filter-duplicates` and `avoid-adding-duplicates` to `true`, because the duplicate detection is done by comparing text values (which are the same).

Proposed solutions:

- either provide a way to pass a duplicate detection function. This way, when detecting duplicates, it is possible to compare the text and the category of the tags, instead of just the text.

- as an alternative, provide a new event 'before-autocomplete-suggestion' so I can filter out invalid (duplicate) suggestions myself. Although this is a useful event, this solution has the downside that the problem still exist if no autocomplete is used, or if `add-only-from-autocomplete` is `false`.

**Comment by JohMun** [comment]
Hi, I will shortly provide a solution with a callback function to detect duplicates. I tell you in this issue, when the new version with that feature is available.

**Comment by JohMun** [comment]
Okay, I recently published the new version [1.5.6](https://github.com/JohMun/vue-tags-input/releases/tag/v1.5.6). Now you can define a custom function to check if a tag is a duplicate. In your case, with those categories, the function would look like this, I think:

```
isDuplicate(tags, tag) {
  const categoryTags = tags.filter(({ category }) => category === tag.category);
  return categoryTags.map(({ text }) => text).indexOf(tag.text) !== -1;
}
```

**Comment by JohMun** [comment]
The function can be registered via the prop `is-duplicate`, see [props](http://www.vue-tags-input.com/#/api/props).

**Comment by fikkatra** [comment]
@JohMun , thanks for looking into this. I tried your solution with the following configuration:

```
:autocomplete-filter-duplicates="true"
:avoid-adding-duplicates="true"
:is-duplicate="isDuplicateTag"
```
and the following function (I kept it simple just to test things):

```
isDuplicateTag(tags, tag) {
	return false;
}
```

However, I'm still unable to select both 'Beatle' tags. Once I select the first 'Beatle' tag, the second one is not suggested in the autocomplete.

**Comment by fikkatra** [comment]
@JohMun Thanks, now it works, the autocomplete initially shows both options, and filters out the options once they are already selected. Great!

One thing I find strange, is that I have to set `:avoid-adding-duplicates="false"` in order for it to work, otherwise I'm not able to select the second tag from the autocomplete (even though it is shown as a suggestion). For me it's not really a problem because I have `:add-only-from-autocomplete="true"`, but I can imagine that it could be a problem for people that have `:add-only-from-autocomplete="false"`.

Once again thanks for this feature!

**Comment by JohMun** [comment]
@fikkatra update to 1.5.9. Then it should also work with `:avoid-adding-duplicates="true"`

**Comment by fikkatra** [comment]
Yup, works like a charm!
