### ISSUE TITLE
How to use vue-tags-input in a form?

### ISSUE THREAD

**Issue by aleehedl** [JohMun/vue-tags-input#4]
I'm interested using this component in a html form. What would be the best way to include the tag-value in a hidden input?

**Comment by JohMun** [comment]
Actually doing something like this would be the best way:

```
<input type="hidden" name="tagValue" v-model="tagModel" />
```

or

```
<input type="hidden" name="tagValue" :value="tagModel" />
```

but according to this, Vue can't bind values to hidden inputs: https://github.com/vuejs/vue/issues/1194
