### ISSUE TITLE
[Question] set autocomplete position at top?

### ISSUE THREAD

**Issue by 1c7** [JohMun/vue-tags-input#40]
### My editor expand to the bottom of the page
![image](https://user-images.githubusercontent.com/1804755/45928744-4c7dde00-bf7b-11e8-9252-a39d2cf4e734.png)

### Auto complete is overflow
![image](https://user-images.githubusercontent.com/1804755/45928746-530c5580-bf7b-11e8-8c27-e0b6b927e8f1.png)

### Question: how do I set auto complete box at top?
![image](https://user-images.githubusercontent.com/1804755/45928762-7f27d680-bf7b-11e8-85e1-92155f20ed8f.png)

Thank you very much!

**Comment by JohMun** [comment]
But be aware, that the autocomplete layer will overflow some tags if the input has multiple lines

**Comment by JohMun** [comment]
I think I add a prop in the next release, which defines the autocomplete position. At default this prop would be `bottom`, but can be changed to `top`.

**Comment by 1c7** [comment]
Thank you!
