### ISSUE TITLE
Avoid using common-used css class names

### ISSUE THREAD

**Issue by luiseok** [JohMun/vue-tags-input#45]
Hello JohMun.
Thanks for sharing this awesome component. vue-tags-input makes me improve productivity.

BTW, I have an issue with css class names. For example, I use a legacy css file which is global style (not scoped) and that file has css class named 'content', 'tag' etc...
As you know, vue-tags-input uses scoped style, and also uses common-used class name like 'content', 'tag'.
I think that the use of common class names can cause mutual interference or conflicts.
Below is the situation I am facing.
![image](https://user-images.githubusercontent.com/3125044/47890431-2872be00-de92-11e8-9a1a-8596a69bb681.png) ![image](https://user-images.githubusercontent.com/3125044/47890450-39bbca80-de92-11e8-90df-e270c08602f3.png)

So....Can I request a pull-request by changing the common-used class names in vue-tags-input to something like `tags--content`, `tags--tag`?
If the class name changes, It might decrease the number of users who will suffer from interference.
Thanks.

**Comment by JohMun** [comment]
Hi, Im aware of this issue and I will fix this in the next major version of vue-tags-input, because unfortunately this will cause breaking changes.

**Comment by luiseok** [comment]
@JohMun Thank you. I will be waiting for the next major update.

**Comment by JohMun** [comment]
[Version 2](https://github.com/JohMun/vue-tags-input/releases/tag/v2.0.0) is now available and all css classes are prefixed with `ti-`. Take a look at [migration](http://www.vue-tags-input.com/#/migration), how to update.
