### ISSUE TITLE
Whats the best way to load tags after initial init?

### ISSUE THREAD

**Issue by ty7466** [JohMun/vue-tags-input#5]
After the component loaded whats the best way to pass information to my component that is using vue-tags-component?

**Comment by JohMun** [comment]
The model you bind to `v-model` is always up to date, because of the two-way-databinding. 
After the tags changes, the event `@tags-changed` emits. The updated tags are passed as parameter.
Here is a working [example](http://www.vue-tags-input.com/#/start)
