### ISSUE TITLE
Mix tags and text

### ISSUE THREAD

**Issue by weislanes** [JohMun/vue-tags-input#50]
Hey, really great tool.

One question: is it possible to mix tags and text in the same input field?  Can't find anything in the docs.

**Comment by JohMun** [comment]
No, it's not possible. A html input field can only hold text. But it's possible to edit tags after creation.

**Comment by weislanes** [comment]
Cool, thanks.

**Comment by cyrilcs-squad** [comment]
also interested to mix text and tags
