### ISSUE TITLE
Long tag

### ISSUE THREAD

**Issue by FredyMM** [JohMun/vue-tags-input#51]
When I create a label with a text string that is too large, the text juts out of the text box.

**Comment by JohMun** [comment]
If you create a string with no space in between, the browser doesn't know where to break the string into a new line. 

The text of tag tag, is wrapped in a span and a div with the class `tag-center`. Just apply this css rule, to enforce a break (maybe you need a stronger css-selector than in this example):
```
.tag-center span {
  word-break: break-all;
}
```
