### ISSUE TITLE
Use css framework to style input box

### ISSUE THREAD

**Issue by SPQRInc** [JohMun/vue-tags-input#52]
Hi everybody,

I'd like to use UIkit (https://getuikit.com/docs) for styling and "look & feel" of my web page (https://getuikit.com/docs/form).

As I am using sass, I would like to extend the classes vue-tags-input uses - but unfortunately I am not very good in css.

Any idea or explanation on how to do that? One big problem: I can not change the size of the placeholder :-/

Any help is highly appreciated!

**Comment by SPQRInc** [comment]
I created a little codepen to demonstrate this: https://codepen.io/spqrinc/pen/vQjRjB

**Comment by SPQRInc** [comment]
Great :-) Now I just have to have a look at the multi-line-feature (as you can see, the border is shown weird, once a second line is added). 

I really appreciate your help!

**Comment by JohMun** [comment]
Ah, I gave `div.input` `height: 40px`, that's why it couldn't grow bigger. Now it should work as expected.

**Comment by JohMun** [comment]
A new version of vue-tags-input is available. Now it adds the css class `ti-focus` to itself if necessary. I updated the [codepen](https://codepen.io/JohMun/pen/YRvgpJ) and the effect shown on focus should work.
