### ISSUE TITLE
insert between tags

### ISSUE THREAD

**Issue by joelarula** [JohMun/vue-tags-input#54]
It could be nice feature to move between tags with arrow keys and insert new tags between existing tags. This  feature allows using tag editor as logical expression editor. It could be achieved moving editor component representation in tags list assuming that only one focus is needed at time :) JohMun! Could i open branch for such feature?

**Comment by JohMun** [comment]
Dublicate of #25. Of course you can create a branch, but be aware that this is a really complex feature and lot of code changes are necessary.

**Comment by joelarula** [comment]
Writing new tags input from scratch is even more complex :) I will try if this can be done

**Comment by JohMun** [comment]
I close this now, because there already exists an issue with that feature request #25
