### ISSUE TITLE
Typing backslash causes Invalid regular expression error

### ISSUE THREAD

**Issue by robfrancken** [JohMun/vue-tags-input#56]
Caught this by chance. Seems to be the case whenever we filter using RexExp and passing it the `tag` string.

Should we be manually stripping the '\', or is there a better way?

**Comment by JohMun** [comment]
Maybe you have the code from [here](http://www.vue-tags-input.com/#/examples/autocomplete). There I can reproduce the issue. However it's not an issue with vue-tags-input itself, it's an issue in the example.

To solve this, you could change your filter function like this:
```
filteredItems() {
  return this.autocompleteItems.filter(i => {
    return i.text.toLowerCase().indexOf(this.tag.toLowerCase()) !== -1;
  });
},
```

**Comment by robfrancken** [comment]
Yes, thanks for updating the example 👍

**Comment by bakztfuture** [comment]
> Maybe you have the code from [here](http://www.vue-tags-input.com/#/examples/autocomplete). This is the function which caused the error:
> 
> ```
> filteredItems() {
>   return this.autocompleteItems.filter(i => new RegExp(this.tag, 'i').test(i.text));
> }
> ```
> 
> However it's not an issue with vue-tags-input itself, it was an issue in the example.
> 
> To solve this, you could change your filter function to this (I already did it in the examples):
> 
> ```
> filteredItems() {
>   return this.autocompleteItems.filter(i => {
>     return i.text.toLowerCase().indexOf(this.tag.toLowerCase()) !== -1;
>   });
> },
> ```

I have added this correction in my code, but I'm still getting this error twice: 
`
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
Vue._render @ vue.runtime.esm.js?2b0e:3544
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
merged @ vue.runtime.esm.js?2b0e:3301
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
patch @ vue.runtime.esm.js?2b0e:6510
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
Vue.$forceUpdate @ vue.runtime.esm.js?2b0e:3963
(anonymous) @ index.js?6435:242
(anonymous) @ index.js?6435:240
(anonymous) @ index.js?6435:119
(anonymous) @ Results.vue?5aba:29
./src/views/Results.vue @ app.js:6772
__webpack_require__ @ app.js:767
hotApply @ app.js:686
(anonymous) @ app.js:343
Promise.then (async)
hotUpdateDownloaded @ app.js:342
hotAddUpdateChunk @ app.js:318
webpackHotUpdateCallback @ app.js:37
(anonymous) @ app.e4e14267ba0b90ad1e6e.hot-update.js:1
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'toLowerCase' of undefined`
