### ISSUE TITLE
Limit number of tags

### ISSUE THREAD

**Issue by SPQRInc** [JohMun/vue-tags-input#58]
Hello everybody :-)

Is it possible to limit the number of tags somehow? I'd like to allow 5 tags :-) 

Thanks in advance :-)

**Comment by JohMun** [comment]
Hi,

sure it's possible. Use the prop `max-tags` to limit the number of tags e.g. `max-tags="3"`. [Here](http://www.vue-tags-input.com/#/api/props) you can find a list describing all available props.
