### ISSUE TITLE
Best practice for loading array of values

### ISSUE THREAD

**Issue by rlightner** [JohMun/vue-tags-input#62]
I have an array of strings `["primary", "overdue", "todo"]` on a property that I'm binding to the `:tags` prop. 

What is the best method for loading this without having to go through an extra step on my side to bind?

**Comment by JohMun** [comment]
There will be an extra step on your side, because vue-tags-input expects an array filled with objects inside, as model for the tags.

But you can easily convert your array:
```javascript
data() {
  return {
    tag: '',
    tags: null,
  },
},
created() {
  // necessary step on your side
  this.tags = ['primary', 'overdue'].map(text => ({ text }));
}
```

**Comment by JohMun** [comment]
Okay, TI think your question is answered. I close this issue now.
