### ISSUE TITLE
Is it possible to customize tag-actions?

### ISSUE THREAD

**Issue by Vivek0047** [JohMun/vue-tags-input#63]
I have a particular scenario where I pull tags from an API, also there are some default tags that should not be removed. 
I need a way to how I can hide the cross button / tag-actions according to my need.
I know this can be done using querySelector, I used to call after an event where tags are added although it does not works as my code works faster than how tags are rendered.

I hope someone helps me with this. Thanks in advance 😃 

Here is what I tried : 
HTML : 
```
<li class="ti-tag ti-valid no-cross"></li>
```

Javascript : 
```
// added a class to ''ti-tag ti-valid' instance.

let elements = document.querySelectorAll('.no-cross')
let actions = [];
Array.from(elements).map(x => actions.push(x.querySelector('.ti-actions')))
actions.map(x => x.parentElement.removeChild(x))
````

**Comment by JohMun** [comment]
I think the fastest and easiest solution would be, to hide the actions with css.  You can define a css class for a tag in your model like this:
```javascript
tags: [{
  text: 'my tags 1',
}, {
  text: 'my tag 2',
  classes: 'no-cross', // will be appended to this tag
}]
```

now you hide the actions with unscoped css:
```css
.my-tags-input .no-cross .ti-actions {
  display: none;
}
```
But be aware, that the user is still able to delete the tag by pressing backspace (you can turn this off with the prop `delete-on-backspace` e.g. `delete-on-backspace="false"`, or you can do a check inside the [hook](http://www.vue-tags-input.com/#/api/events) `before-deleting-tag` if the tag can be deleted).  

If you like to customize the actions for a tag even more. Take a look at the slot `tag-actions`, see [slots](http://www.vue-tags-input.com/#/api/slots).
