### ISSUE TITLE
edit tag mode doesn't show text

### ISSUE THREAD

**Issue by ktmellow** [JohMun/vue-tags-input#64]
Repro steps
1. I click the text to edit tag. 
2. Type new text. Cannot see text while editing. 
3. Press enter and the invisible text is submitted as a tag. Tag becomes visible.

![Video of issue](https://media.giphy.com/media/7Tf0d8EwgLwNSnADV5/giphy.gif)

`        <vue-tags-input
              v-model="button"
              :tags="buttonTags"
              @tags-changed="(newButtons) => updateTags(newButtons)"
              :allow-edit-tags=true
              placeholder="Add button text...">
            </vue-tags-input>`

Does this happen to anybody? I feel like maybe I missed something but not sure what.

**Comment by JohMun** [comment]
I cannot reproduce the issue, sry. Could you create a [codepen](https://codepen.io/)? Then I may have a chance to find out, why the compontent behave in this way.
