### ISSUE TITLE
Include Tags into normal input field

### ISSUE THREAD

**Issue by Issabln** [JohMun/vue-tags-input#66]
Hi,

is there a way to include your tags into a normal input field? Like writing an normal text and only set a tag if I enter a certain key, basically like hashtags, if I enter a "#" it should trigger the tags.

**Comment by JohMun** [comment]
It's possible to define trigger keys like '#', which create tags out of the input, if those keys are pressed. But it's not possible to mix text and tags together like: some text [I am a tag] more text ... [and a tag again].
