### ISSUE TITLE
Property $attrs not defined

### ISSUE THREAD

**Issue by coreation** [JohMun/vue-tags-input#67]
Hi there,

First off, great package, I'm running the 1.6 version and the amount of things you can configure, is really a treat, so thanks for making and supporting this!

On installing 2.0, I get the following error in my console, using Vue 2.2.x:

[Vue warn]: Property or method "$attrs" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <VueTagsInput> at vue-tags-input/vue-tags-input.vue)

I might be mistaking, but the usage of $attrs the way you do it, that's only available in Vuejs 2.4 right?
If so, it might be useful to document it on the README page somewhere :)

**Comment by JohMun** [comment]
Yes, you are right. Thx for telling me. I add a note in the readme and change the required vue version in the package.json.

**Comment by coreation** [comment]
Thanks a bunch! For now I'm using the v1.6.0 version, works like a charm <3
