### ISSUE TITLE
Array of strings for the collection

### ISSUE THREAD

**Issue by ChunAllen** [JohMun/vue-tags-input#69]
Is there an option wherein when I add new tag it will just push to the array? 

Currently my vue-input-tag is this: 
```
 <vue-tags-input
      v-model="tag"
      :tags="interests"
      @tags-changed="newTags => interests = newTags"
    />

export default {
    name: 'UserForm',
    data() {
       return  {
          tag: '', 
          interests: []
       }
    }
}
```
when I add new string to the input the for example `Hello` the tags array will be like this
`[{"text":"hello","tiClasses":["ti-valid"]}]`

my expectation will be just like this: 
`['hello']`

because when I save it on my no-sql database it will be saved as `array of strings`

**Comment by JohMun** [comment]
If you like to fill up vue-tags-input with tags on startup, then you should convert your array of strings to the format which is required by the component.

```javascript
created() {
  this.tags = myArrayFromDb.map(string =>({ text: string }));
},
```

**Comment by sleepyfoodie** [comment]
If you just want the array without the object, would this work?
```
 <vue-tags-input
      v-model="tag"
      :tags="interests"
      @tags-changed="newTags => formatTags(newTags)"
   />`

export default {
    name: 'UserForm',
    data() {
       return  {
          tag: '', 
          interests: []
       }
    },
   methods: {
      formatTags(newInterests) {
         this.interests = newInterests.map(interest => interest.text);
      }
   }
}
```
