### ISSUE TITLE
Duplicates are being allowed if tag contains whitespace

### ISSUE THREAD

**Issue by orim181** [JohMun/vue-tags-input#76]
Adding the same tag with differing whitespaces at the end of the string allows duplicates to be stored.

Tags added:
"test " <-- one whitespace
"test  " <-- two whitespaces
"test   " <-- three whitespaces

![image](https://user-images.githubusercontent.com/11587953/53106681-8d195d80-3501-11e9-95d6-58213ed921fd.png)

They all get translated to "test " with one whitespace

I was expecting the whitespace to either be removed, treated as part of the tag, or to fail the dupe check but none of that is occurring. You can try this on the homepage example or in your own example.

**Comment by JohMun** [comment]
I tried it out [here](http://www.vue-tags-input.com/#/) and the whitespace is treated as a part of the tag. If I enter `text··` (· = whitespace), I can't enter it again. Now if I click on the tag to open the edit mode, both whitespaces are in the input.

**Comment by orim181** [comment]
Thanks for responding. The problem isn't that you can't enter it again actually, but if you look at the captured tags in the Vue component, are they exactly what you entered or did the extra whitespaces all get trimmed to a single space?

**Comment by orim181** [comment]
Discovered that the Vue Dev Tools was actually misrepresenting the number of trailing whitespaces.

Closing issue. Not a bug!

**Comment by alexcroox** [comment]
For me finding this in 2022 wondering why whitespace isn't auto trimmed, the quickest workaround I found was to make the space key auto add the tag:

`:addOnKey="[13, 188, 32]"`

13 = enter
188 = comma
32 = space
