### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by naveensky** [JohMun/vue-tags-input#8]
Hi,

Does this support SSR for usage in frameworks this Nuxt.js. 

Thanks,

**Comment by naveensky** [comment]
@JohMun - I tried it with `ssr` as `false`. It works pretty good in prod but gives vue warning on development mode.

**Comment by JohMun** [comment]
Okay, in the next days I check the behaviour of `vue-tags-input` in combination with SSR

**Comment by JohMun** [comment]
@naveensky the warning won't show up if you wrap `vue-tags-input` in `no-ssr` elements. For example like this:

```
<no-ssr>
    <vue-tags-input
      v-model="tag"
      :tags="tags"
      @tags-changed="newTags => tags = newTags"
    />
  </no-ssr>
```

**Comment by outOFFspace** [comment]
And what if I don't use Nuxt?

**Comment by JensvdHeydt** [comment]
@outOFFspace You don't need Nuxt to use the no-ssr - Tag. No-SSR is actually a VueJS plugin that you can include yourself.
