### ISSUE TITLE
fontawesome icons

### ISSUE THREAD

**Issue by niouraki** [JohMun/vue-tags-input#86]
Can I add a fontawesome icon in the placeholder?

**Comment by JohMun** [comment]
You could use the slot `tag-actions` and take your own icons. [Here](http://www.vue-tags-input.com/#/api/slots) are the API docs, where the `slot-props` are explained. [Here](http://www.vue-tags-input.com/#/examples/templates) you can find an example how to use the slots provided by the component.

**Comment by pranavkumar389** [comment]
How to achieve it. Sample code will help me :)
