### ISSUE TITLE
autocomplete focus state incompatible with vue2.6.x

### ISSUE THREAD

**Issue by qiangbro** [JohMun/vue-tags-input#87]
just like the first sample in this page: http://www.vue-tags-input.com/#/examples/autocomplete
when i switch vue version to 2.6.10, an incompatible thing occurs:
after i selected an item in the autocomplete-items List, the vue-tags-input component will lose focus state  (though the tag-input element is still in focus state) , then i type in the next keyword, however the autocomplete function will not be triggered.

i have to click outside and then click inside again, then the vue-tags-input component will get the focus state, then the autocomplete function will be triggered.

when i switch to vue 2.5.16, everything works fine.

**Comment by ianemv** [comment]
I'm using 2.5.17 but autocomplete is still showing.

![image](https://user-images.githubusercontent.com/790249/56776445-13526880-67ff-11e9-86ce-4937678decaf.png)

**Comment by TheFrankman** [comment]
@qiangbro - I can confirm that i'm having the same issue.
@JohMun - Any chance you can take a look at this.

I've tried a hacky approach of doing this : 

```
tagsChanged(newTags) {
     this.tags = newTags;
     $('input#item_tags').blur();
}
```

This forces the user to have to re-click the tags input.

However if I also do : `$('input#item_tags').focus();` the autocomplete still doesn't show.

**Comment by stefanwuthrich** [comment]
Knowing it's not the best solution, but as long this pull request is not merged and component is broken for new vue.js version, i did it and you can npm install @altafino/vue-tags-input
https://github.com/altafino/vue-tags-input
But I will not maintain this. Use it just, like me, until original repo is updated.
