### ISSUE TITLE
How to make the width 100%

### ISSUE THREAD

**Issue by mbalandis** [JohMun/vue-tags-input#9]
First of all thanks for creating this. It is working really well! 

HOWEVER...

I can't figure out how to set width of the component. I tried absolutely everything and no matter what it maxes out to 450px and goes to another line when adding tags. Where is no setting on this or documentation on this. I managed to make it px specific at some point (can't remember how) but it wasn't responsive and was broken anyway. 
This is how width is stuck when I use component:

http://prntscr.com/jmgmpc

**Comment by JohMun** [comment]
@mbalandis The component has the css class `vue-tags-input` with a `max-width` of `450px`. You just have to use a stronger css selector and overwrite the rule. For example like this:

```
#my-custom-wrapper .vue-tags-input {
  max-width: none;
  width: 100%;
}
```

**Comment by mbalandis** [comment]
@JohMun thank you for the reply. Didn't try that exact combination so I will give that a go.

**Comment by mbalandis** [comment]
@JohMun It didn't work at start but then I figured out it must not have a space in between so correct answer is:

```
#my-custom-wrapper.vue-tags-input {
  max-width: none;
  width: 100%;
}
```
