### ISSUE TITLE
Prediction not showing after selecting one tag with mouse click

### ISSUE THREAD

**Issue by keviinnch** [JohMun/vue-tags-input#92]
Step to reproduce the bug:
1. Type a tag (e.g : Spain).
2. Select one of the tag that showing with a mouse click.
3. Type another tag.
4. Prediction tag doesn't show

Here is the [codepen](https://codepen.io/keviinnch/pen/qGPQvq?editors=1010).

Note:
1. If I select the tag by pressing 'Enter' key, the next typed tag will show the prediction.
2. If I click somewhere else outside the input bar, then click inside the input bar and start typing, the prediction will show too. (Edit: Other action like Alt+tab in and out will also fix it)

**Comment by keviinnch** [comment]
I can use `autocompleteAlwaysOpen` as a workaround, but it's not a correct solution (?)

**Comment by JohMun** [comment]
Maybe #89 fixes this issue
