### ISSUE TITLE
Autocomplete toLowerCase error, unable to "filter" autocomplete suggestions

### ISSUE THREAD

**Issue by bakztfuture** [JohMun/vue-tags-input#95]
I have added this correction for the basic autocomplete example ( #78 ) in my code, but I'm still getting this error twice:
```
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'toLowerCase' of undefined
```

has any one been able to get basic autocomplete working?  My version shows all the tags in the dropdown at once, and doesn't filter the possible results as the user types, in addition to the error above.  I have a basic vuejs project running and tried to create the basic example in the docs.

would appreciate any feedback, currently working on a time-sensitive project

**Comment by aleahy** [comment]
This worked for me. If your 'i.text' is undefined, are you sure that your autocompleteItems array is an array of objects with property 'text' containing the string for the tag?

**Comment by bakztfuture** [comment]
Yes, I've been using the items included in the data function in the example.  Eg. The countries Spain, etc.

**Comment by aleahy** [comment]
Here is the complete example with the correct code. It works fine for me.

```
<template>
  <div>
    <vue-tags-input
      v-model="tag"
      :tags="tags"
      :autocomplete-items="filteredItems"
      @tags-changed="newTags => tags = newTags"
    />
  </div>
</template>

<script>
import VueTagsInput from '@johmun/vue-tags-input';

export default {
  components: {
    VueTagsInput,
  },
  data() {
    return {
      tag: '',
      tags: [],
      autocompleteItems: [{
        text: 'Spain',
      }, {
        text: 'France',
      }, {
        text: 'USA',
      }, {
        text: 'Germany',
      }, {
        text: 'China',
      }],
    };
  },
  computed: {
    filteredItems() {
      return this.autocompleteItems.filter(i => {
        return i.text.toLowerCase().indexOf(this.tag.toLowerCase()) !== -1;
      });
    },
  },
};
</script>
```

**Comment by bakztfuture** [comment]
you are right ... I had the worst typo buried in my code!  Thanks for taking a look.
