### ISSUE TITLE
CSS Styling of Tags Having No Effect

### ISSUE THREAD

**Issue by arpollock** [JohMun/vue-tags-input#99]
Love the component, but I am having difficulty styling the background color of the tags. I can change the style of the whole tags input (i.e I can change the width of the vue-tags-input object and the font size within that), but I can't get the color of the tags to change from the default #5C6BC0.

I am just following the example here: http://www.vue-tags-input.com/#/examples/styling with no luck. I was initially using the createTags helper (and I thought this was having an effect), but even when I give all of the tags a custom class without using the helper, the custom class styling does not appear. And, when I inspect the elements this class isn't even on the li elements (just the ti-tag and ti-valid classes). 

The only effect I can get styling wise is putting the string inline with the style attribute, but this overrides the default delete styling which I like. I have even tried using !important on the class .ti-tags with my internal style sheet with no luck. Any suggestions? 
I am using https://github.com/kaorun343/vue-property-decorator but I don't think this should have an effect on the styling.

**Comment by arpollock** [comment]
Update with the investigation: confirmed that the applied class is getting overwritten at some point. When I access the tags tiClasses array, ti-valid is the only one, even though I applied a 'custom-class' class when I created the array of objects.

**Comment by arpollock** [comment]
Solution: don't let scoped on your style sheet ruin your day

**Comment by albertpratomo** [comment]
How to override the scoped original `vue-tags-input.scss`?

**Comment by Jonaskp-reply** [comment]
Same problem for me. On localhost css changes work, but when deploying, css changes are overwritten and not working. Any solution on this?
